CREATE TABLE `proposals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int NOT NULL,
	`serviceType` enum('business_health_check','starting_business_logic','brand_identity','business_takeoff','consultation') NOT NULL,
	`title` varchar(500) NOT NULL,
	`language` enum('en','ar') NOT NULL DEFAULT 'en',
	`status` enum('draft','sent','accepted','rejected') NOT NULL DEFAULT 'draft',
	`executiveSummary` text,
	`clientBackground` text,
	`serviceDescription` text,
	`methodology` text,
	`deliverables` text,
	`timeline` text,
	`investment` text,
	`whyPrimoMarca` text,
	`terms` text,
	`customNotes` text,
	`price` decimal(12,2),
	`currency` varchar(10) DEFAULT 'EGP',
	`pdfUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `proposals_id` PRIMARY KEY(`id`)
);
