CREATE TABLE IF NOT EXISTS `blog_posts` (
  `id` int AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `slug` varchar(255) NOT NULL,
  `title_ar` varchar(500) NOT NULL,
  `title_en` varchar(500) NOT NULL,
  `excerpt_ar` text,
  `excerpt_en` text,
  `content_ar` text NOT NULL,
  `content_en` text NOT NULL,
  `cover_image` varchar(1000),
  `category` varchar(100),
  `tags` varchar(500),
  `published` int NOT NULL DEFAULT 0,
  `published_at` timestamp,
  `seo_title_ar` varchar(500),
  `seo_title_en` varchar(500),
  `seo_desc_ar` text,
  `seo_desc_en` text,
  `reading_time_min` int DEFAULT 5,
  `view_count` int NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT (now()),
  `updated_at` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
