import { eq, desc, and, like } from "drizzle-orm";
import { knowledgeEntries, InsertKnowledgeEntry, KnowledgeEntry } from "../../drizzle/schema";
import { getDb } from "./index";

export async function createKnowledgeEntry(data: InsertKnowledgeEntry): Promise<number> { const db = await getDb(); if (!db) return 0; const result = await db.insert(knowledgeEntries).values(data); return result[0].insertId; }
export async function getKnowledgeEntries(filters?: { category?: string; industry?: string; market?: string; search?: string }): Promise<KnowledgeEntry[]> { const db = await getDb(); if (!db) return []; const conditions: ReturnType<typeof eq>[] = [eq(knowledgeEntries.isActive, 1)]; if (filters?.category) conditions.push(eq(knowledgeEntries.category, filters.category as "methodology" | "general" | "case_study" | "framework" | "lesson_learned" | "market_insight" | "competitor_intel" | "client_pattern" | "template")); if (filters?.industry) conditions.push(eq(knowledgeEntries.industry, filters.industry)); if (filters?.market) conditions.push(eq(knowledgeEntries.market, filters.market)); if (filters?.search) conditions.push(like(knowledgeEntries.title, `%${filters.search}%`)); return db.select().from(knowledgeEntries).where(and(...conditions)).orderBy(desc(knowledgeEntries.updatedAt)); }
export async function getKnowledgeEntryById(id: number): Promise<KnowledgeEntry | null> { const db = await getDb(); if (!db) return null; const rows = await db.select().from(knowledgeEntries).where(eq(knowledgeEntries.id, id)).limit(1); return rows[0] || null; }
export async function updateKnowledgeEntry(id: number, data: Partial<InsertKnowledgeEntry>): Promise<void> { const db = await getDb(); if (!db) return; await db.update(knowledgeEntries).set(data).where(eq(knowledgeEntries.id, id)); }
export async function deleteKnowledgeEntry(id: number): Promise<void> { const db = await getDb(); if (!db) return; await db.update(knowledgeEntries).set({ isActive: 0 }).where(eq(knowledgeEntries.id, id)); }
export async function getKnowledgeStats() { const db = await getDb(); if (!db) return { total: 0, byCategory: {} as Record<string, number> }; const entries = await db.select().from(knowledgeEntries).where(eq(knowledgeEntries.isActive, 1)); const byCategory: Record<string, number> = {}; for (const e of entries) { byCategory[e.category] = (byCategory[e.category] || 0) + 1; } return { total: entries.length, byCategory }; }
export async function getKnowledgeForContext(industry?: string, market?: string): Promise<string> { const db = await getDb(); if (!db) return ''; const conditions: ReturnType<typeof eq>[] = [eq(knowledgeEntries.isActive, 1)]; if (industry) conditions.push(eq(knowledgeEntries.industry, industry)); if (market) conditions.push(eq(knowledgeEntries.market, market)); const entries = await db.select().from(knowledgeEntries).where(and(...conditions)).orderBy(desc(knowledgeEntries.updatedAt)).limit(20); if (entries.length === 0) return ''; let context = '\n## KNOWLEDGE BASE (Curated Insights)\n\n'; for (const entry of entries) { context += `### [${entry.category.toUpperCase()}] ${entry.title}\n${entry.content}\n\n`; } return context; }
